### ISSUE TITLE
Border background

### ISSUE THREAD

**Issue by tungmeister** [pacjo/google_dark_animated#2]
Hi, could you advise where in the code this border/background is defined so I can remove it? It's not present in other themes and is spoiling elements of my lovelace.
![image](https://user-images.githubusercontent.com/127809/142761067-5be61fd2-87cc-4169-89a0-44fe2ad864fc.png)

**Comment by pacjo** [comment]
Honestly I don't even have an idea. This theme is identical to [https://github.com/JuanMTech/google_dark_theme](url) apart from some changed icons. JuanMTech's repo would probably be the best place to ask.
